### ISSUE TITLE
Special html char invisible from right click menu

### ISSUE THREAD

**Issue by jihadjo** [thaneuk/brackets-special-html-chars#11] opened 2015-04-27 17:10 UTC
Impossible to open the html special characters with the right click menu.
I need to uninstall and reinstall it again to make it work.

**Comment by thaneuk** [comment] 2015-04-28 00:31
I've tried to reproduce but cannot. Using latest Release 1.3 build 1.3.0-16022 (release cd0a6aae5) on Windows 8.1 I am having no issues, re-installing and testing repeated closing/opening of brackets gives me no issues, errors or warnings relating to the extension.

Perhaps if you can give more information, relating to your OS, version of Brackets and the errors you are getting in debug console that relate so I can investigate further.

Have you installed any other extensions lately, I can look into possible conflicts?

**Comment by thaneuk** [comment] 2015-04-30 00:07
I have now tested on Mac and still unable to reproduce.

**Comment by thaneuk** [comment] 2015-05-09 17:27
With no further details I am closing this issue.

**Closed by thaneuk** 2015-05-09 17:27 UTC
